name: TPM Tests (Nix)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tpm-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Run TPM tests
        run: |
          nix-shell -p go swtpm tpm2-tools tpm2-abrmd tpm2-openssl openssl softhsm gnutls dbus --run '
            dbus-run-session -- bash -c "
              export OPENSSL_MODULES=\$(nix-build --no-out-link \"<nixpkgs>\" -A tpm2-openssl)/lib/ossl-modules
              export TPM2OPENSSL_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd2321,bus_type=session
              export TPM2TOOLS_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd2321,bus_type=session
              make test-tpm-signer
            "
          '
