name: TPM Tests (Nix)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tpm-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Setup dbus config
        run: |
          sudo mkdir -p /etc/dbus-1
          echo '<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
          <busconfig>
            <type>session</type>
            <listen>unix:tmpdir=/tmp</listen>
            <policy context="default">
              <allow send_destination="*" eavesdrop="true"/>
              <allow eavesdrop="true"/>
              <allow own="*"/>
            </policy>
          </busconfig>' | sudo tee /etc/dbus-1/session.conf

      - name: Run TPM tests
        run: |
          nix-shell -p go swtpm tpm2-tools tpm2-abrmd tpm2-openssl softhsm gnutls dbus --run '
            dbus-run-session -- bash -c "
              TPM2_OPENSSL=\$(nix-build --no-out-link \"<nixpkgs>\" -A tpm2-openssl)
              export OPENSSL_MODULES=\$TPM2_OPENSSL/lib/ossl-modules
              export PATH=\$TPM2_OPENSSL/bin:\$PATH

              rm -rf tst/swtpm

              SWTPM_PREFIX=\"TPM2TOOLS_TCTI=swtpm:host=localhost,port=2321 TPM2OPENSSL_TCTI=swtpm:host=localhost,port=2321 OPENSSL_MODULES=\$OPENSSL_MODULES\"

              START_SWTPM_TCP=\"if ! swtpm_ioctl --tcp 127.0.0.1:2322 -g >/dev/null 2>/dev/null; then
                mkdir -p \$(pwd)/tst/swtpm
                swtpm socket --tpm2 --tpmstate dir=\$(pwd)/tst/swtpm --server type=tcp,port=2321 --ctrl type=tcp,port=2322 --flags not-need-init,startup-clear -d
                sleep 1
                TPM2TOOLS_TCTI=swtpm:host=localhost,port=2321 TPM2OPENSSL_TCTI=swtpm:host=localhost,port=2321 OPENSSL_MODULES=\$OPENSSL_MODULES tpm2_dictionarylockout -s -t 0
              fi\"

              make SWTPM_PREFIX=\"\$SWTPM_PREFIX\" START_SWTPM_TCP=\"\$START_SWTPM_TCP\" test-tpm-signer
            "
          '
