name: TPM Tests (Nix)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tpm-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Cache nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: nix-${{ runner.os }}-${{ hashFiles('shell.nix') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Build nix environment
        run: nix-shell --run "echo 'Environment ready'"

      - name: Setup dbus config
        run: |
          sudo mkdir -p /etc/dbus-1
          echo '<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
          <busconfig>
            <type>session</type>
            <listen>unix:tmpdir=/tmp</listen>
            <policy context="default">
              <allow send_destination="*" eavesdrop="true"/>
              <allow eavesdrop="true"/>
              <allow own="*"/>
            </policy>
          </busconfig>' | sudo tee /etc/dbus-1/session.conf

      - name: Run TPM tests
        run: |
          nix-shell --run '
            dbus-run-session -- bash -c "
              TPM2_OPENSSL=\$(nix-build --no-out-link \"<nixpkgs>\" -A tpm2-openssl)
              TPM2_TSS=\$(nix-build --no-out-link \"<nixpkgs>\" -A tpm2-tss)
              OPENSSL=\$(nix-build --no-out-link \"<nixpkgs>\" -A openssl)
              export PATH=\$OPENSSL/bin:\$PATH
              export OPENSSL_MODULES=\$TPM2_OPENSSL/lib/ossl-modules
              export LD_LIBRARY_PATH=\$TPM2_TSS/lib:\${LD_LIBRARY_PATH:-}

              rm -rf tst/swtpm

              # Start swtpm
              mkdir -p \$(pwd)/tst/swtpm
              swtpm socket --tpm2 --tpmstate dir=\$(pwd)/tst/swtpm --server type=tcp,port=2321 --ctrl type=tcp,port=2322 --flags not-need-init,startup-clear -d
              sleep 1

              # Start tpm2-abrmd resource manager
              tpm2-abrmd --tcti=swtpm:host=localhost,port=2321 --allow-root --session --flush-all &
              sleep 2

              # Export TPM env vars
              export TPM2TOOLS_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd,bus_type=session
              export TPM2OPENSSL_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd,bus_type=session

              # Verify env vars
              echo \"Using openssl: \$(which openssl)\"
              echo \"PATH=\$PATH\"
              echo \"OPENSSL_MODULES=\$OPENSSL_MODULES\"
              echo \"Checking OpenSSL providers:\"
              openssl list -providers -verbose

              # Configure dictionary lockout
              tpm2_dictionarylockout -s -t 0

              # Verify PATH right before make
              echo \"PATH before make: \$PATH\"
              echo \"which openssl before make: \$(which openssl)\"

              # Run tests
              make START_SWTPM_TCP=\"true\" SWTPM_PREFIX=\"\" test-tpm-signer
            "
          '
