name: TPM Tests (Nix)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tpm-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Setup dbus config
        run: |
          sudo mkdir -p /etc/dbus-1
          echo '<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
          <busconfig>
            <type>session</type>
            <listen>unix:tmpdir=/tmp</listen>
            <policy context="default">
              <allow send_destination="*" eavesdrop="true"/>
              <allow eavesdrop="true"/>
              <allow own="*"/>
            </policy>
          </busconfig>' | sudo tee /etc/dbus-1/session.conf

      - name: Run TPM tests
        run: |
          nix-shell -p go swtpm tpm2-tools tpm2-abrmd tpm2-openssl softhsm gnutls dbus --run '
            dbus-run-session -- bash -c "
              TPM2_OPENSSL=\$(nix-build --no-out-link \"<nixpkgs>\" -A tpm2-openssl)
              export OPENSSL_MODULES=\$TPM2_OPENSSL/lib/ossl-modules
              export PATH=\$TPM2_OPENSSL/bin:\$PATH

              rm -rf tst/swtpm

              # Start swtpm
              mkdir -p \$(pwd)/tst/swtpm
              swtpm socket --tpm2 --tpmstate dir=\$(pwd)/tst/swtpm --server type=tcp,port=2321 --ctrl type=tcp,port=2322 --flags not-need-init,startup-clear -d
              sleep 1

              # Start tpm2-abrmd resource manager
              tpm2-abrmd --tcti=swtpm:host=localhost,port=2321 --allow-root --session --flush-all &
              ABRMD_PID=\$!
              sleep 2

              # Configure dictionary lockout and run tests
              TPM2TOOLS_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd,bus_type=session tpm2_dictionarylockout -s -t 0

              make \
                START_SWTPM_TCP=\"true\" \
                SWTPM_PREFIX=\"TPM2TOOLS_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd,bus_type=session TPM2OPENSSL_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd,bus_type=session OPENSSL_MODULES=\$OPENSSL_MODULES\" \
                test-tpm-signer

              # Cleanup
              kill \$ABRMD_PID 2>/dev/null || true
            "
          '
